# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176948d2c27c13ffa441bb1adf2d8b95a46a9f6eedfdf403579a388ff5d417a5f26e8347a3537391d842485dd402bb285cd6c19666e83c316fa9c3e5d0743e38

test:
  secret_key_base: cad3cdfd318b8d092559b0360a0c8629e2e3eb039ed496cc3e9de8d41028c4bd042ed4702ff6aa916293f234a2d2a5e14621c9c2894fd9f4c3ee682b61c9bf28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
